# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af10087297a41f1a3d3bd3e39e5e1dc2f7510850c352418aa23821523c3d633643f8c619ae0055cc0d6866713d5304f4f4c46757b60f5d122037e0605dfad2b7

test:
  secret_key_base: 3cdc940c448d31795e3b11b971543bba4681992c51e7cc71ba056c5d54b695c18c243bf186aeed0d9818def4566f3dc7c3df6393e72f3fe2c800002bae2335e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
